### ISSUE TITLE
启动容器后循环Illegal instruction

### ISSUE THREAD

**Issue by kid101x** [eMUQI/baidunetdisk-arm64-vnc#5]
日志报错部分为：

```
[supervisor  ] all services started.
[app         ] ndevice name: eth0
[app         ] Illegal instruction
[supervisor  ] service 'app' exited (with status 132).
[supervisor  ] service 'app' exited, shutting down...
[supervisor  ] stopping service 'jwm'...
[supervisor  ] service 'jwm' exited (with status 0).
[supervisor  ] stopping service 'nginx'...
[supervisor  ] service 'nginx' exited (with status 0).
[supervisor  ] stopping service 'xvnc'...
[xvnc        ] Thu Mar 21 01:26:10 2024
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:nan ratio)
[supervisor  ] service 'xvnc' exited (with status 0).
[finish      ] executing container finish scripts...
[finish      ] all container finish scripts executed.
[init        ] container is starting...
```

arm64软路由，root用户UID=0，docker-compost：

```
version: "3.8"
services:
  baidunetdisk-vnc:
    image: emuqi/baidunetdisk-arm64-vnc:latest
    container_name: baidunetdisk-vnc
    environment:
      - USER_ID=0
      - GROUP_ID=0
    volumes:
      - /mnt/sata1/Configs/bdnetdisk-config:/config
      - /mnt/sata1/Baidu-downloads:/config/baidunetdiskdownload
    ports:
      - "15800:5800" # noVNC 端口 按需要修改冒号前面端口
      - "15900:5900" # VNC 端口 按需要修改冒号前面端口
    restart: unless-stopped
```
